### ISSUE TITLE
all sections are empty when connected via Android Auto

### ISSUE THREAD

**Issue by meiser79** [vivizzz007/vivi-music#117]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/vivizzz007/vivi-music/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Connect your phone via Android Auto.
2. Open the vivi app.
3. Try to find some content in the sections Songs, Artists, Albums.

### Expected behavior

When connected via Android Auto, I should see some content in the sections Songs, Artists, Albums.

### Actual behavior

When connected via Android Auto, the sections Songs, Artists, Albums are empty.

### Screenshots/Screen recordings

<img width="1280" height="794" alt="Image" src="https://github.com/user-attachments/assets/0c614aa1-7380-43ea-9b02-23b51bf75fdc" />

<img width="1280" height="821" alt="Image" src="https://github.com/user-attachments/assets/4956b423-5e51-4965-b79f-8291326a803c" />

### Logs

tbd

### music version

4.0.4

### Android version

Android 16

**Comment by ColonelKurtzKim** [comment]
Hi!
How did you connect the VIVI app on Andropid Auto?

**Comment by meiser79** [comment]
You need to enable the developer options in the AA app on the smartphone and then enable "Unknown sources". Then, you can use the "customize launcher" option in the AA settings to enable the vivi app and change the position on the AA screen.

Details under e.g. https://www.devicemag.com/android-auto-application-mode-developer/

**Comment by ColonelKurtzKim** [comment]
Great!Thank you so much!
I was close to this solution, but I didn't ready "origini sconosciute" that stay in my Developer Italian Option :-)
Thank you!

**Comment by meiser79** [comment]
BTW, if you need a good way to test Android Auto, I recommend using [this](https://github.com/andreknieriem/headunit-revived) project. You can run it in self-mode to verify your implementation.

**Comment by T-Boyke** [comment]
@vivizzz007 CLOSE

**Comment by meiser79** [comment]
Hi @T-Boyke, may I kindly ask why it was closed? The issue is not fixed.

**Comment by ColonelKurtzKim** [comment]
It's my fault and my English. The issue is fixed by this

> You need to enable the developer options in the AA app on the smartphone and then enable "Unknown sources". Then, you can use the "customize launcher" option in the AA settings to enable the vivi app and change the position on the AA screen.
> 
> Details under e.g. https://www.devicemag.com/android-auto-application-mode-developer/

**Comment by meiser79** [comment]
Sorry, but you hijacked my bugreport with your issue which has nothing to do with what I reported.

My bugreport is about empty sections, and this issue is still there.

@T-Boyke, could you please re-open the issue? Thanks!
