### ISSUE TITLE
Online music response code 403

### ISSUE THREAD

**Issue by Trisn0802** [vivizzz007/vivi-music#214]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/vivizzz007/vivi-music/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

After I install Vivi music, after I logged in into my YouTube account and trying to play the music I got an error "Respond code: 403"

### Expected behavior

It should work like this image below.

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/3b35818e-591b-431d-8cc7-5367acf1485f" />

### Actual behavior

This happened instead

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/163164bb-e30b-4b78-b3ed-23895f02b99d" />

### Screenshots/Screen recordings

This is the second bug

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/9d6e2f60-039d-4411-a458-c950c79f7050" />

### Logs

Can't find the log

### vivimusic version

5.0.0

### Android version

Android 13

### Additional information

Cusrom: Evolution X
Kernel: 6.15.4-perf+

**Comment by vivizzz007** [comment]
1) I have checked and played its working perfectly fine 
2)The OTA is showing becoz the rate limit ended within short period it would show app is up-to date

**Comment by Trisn0802** [comment]
> 1. I have checked and played its working perfectly fine
>    2)The OTA is showing becoz the rate limit ended within short period it would show app is up-to date

Ok check update is working now, but I still getting response code: 403, do u have any suggestions what I'm going to do?

**Comment by Trisn0802** [comment]
Actually I'm able to listen some of the music like this Minecraft music, but it's not all of them idk why

https://github.com/user-attachments/assets/51cf00b7-4ba8-48a2-88db-bbaada0e232b

**Comment by vivizzz007** [comment]
grap log.

**Comment by privacyfreak84** [comment]
Yeah same thing's happening with Outertune

**Comment by Trisn0802** [comment]
Log

=== CRASH REPORT ===
Timestamp: 2025-12-31 17:24:49

=== DEVICE INFO ===
Device: Xiaomi 2107113SG
Android Version: 13 (API 33)
Brand: Xiaomi
Product: evolution_vili
CPU ABI: arm64-v8a, armeabi-v7a, armeabi

=== APP INFO ===
Package: com.vivi.vivimusic
Version: 5.0.0 (59)

=== THREAD INFO ===
Thread Name: main
Thread ID: 2

=== EXCEPTION ===
Exception Type: android.app.ForegroundServiceStartNotAllowedException
Message: startForegroundService() not allowed due to mAllowStartForeground false: service com.vivi.vivimusic/com.music.vivi.playback.MusicService

=== STACK TRACE ===
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.vivi.vivimusic/com.music.vivi.playback.MusicService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4816)
	at android.os.Parcel.readParcelable(Parcel.java:4778)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5337)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1901)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1877)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at d8.t1.d(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:39)
	at d8.q1.run(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:80)
	at w5.a0.L(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:22)
	at d8.c0.execute(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:33)
	at d8.n.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:49)
	at pc.u.run(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:615)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7966)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by Trisn0802** [comment]
Log Cat

--------- beginning of main
12-31 17:24:44.291 D/YTPlayerUtils(10145): Player response status not OK: LOGIN_REQUIRED, reason: Sign in to confirm you’re not a bot
12-31 17:24:44.291 D/YTPlayerUtils(10145): Trying fallback client 11/11: WEB_CREATOR
12-31 17:24:44.291 D/YTPlayerUtils(10145): Fetching player response for fallback client: WEB_CREATOR
12-31 17:24:44.440 D/YTPlayerUtils(10145): Player response status OK for client: WEB_CREATOR
12-31 17:24:44.449 D/YTPlayerUtils(10145): Finding format with audioQuality: HIGH, network metered: false
12-31 17:24:44.449 D/YTPlayerUtils(10145): Selected format: audio/webm; codecs="opus", bitrate: 145448
12-31 17:24:44.449 D/YTPlayerUtils(10145): Format found: audio/webm; codecs="opus", bitrate: 145448
12-31 17:24:44.449 D/YTPlayerUtils(10145): Finding stream URL for format: audio/webm; codecs="opus", videoId: gGHU9TSUdVQ
12-31 17:24:44.677 D/YTPlayerUtils(10145): Stream URL obtained successfully
12-31 17:24:44.678 D/YTPlayerUtils(10145): Stream expires in: 21540 seconds
12-31 17:24:44.678 D/YTPlayerUtils(10145): Using last fallback client without validation: WEB_CREATOR
12-31 17:24:44.678 D/YTPlayerUtils(10145): Successfully obtained playback data with format: audio/webm; codecs="opus", bitrate: 145448
12-31 17:24:44.708 W/MusicService(10145): setupLoudnessEnhancer: loudnessDb is null, enhancer disabled
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145): Playback error
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):   d6.p: Source error
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at d6.q0.p(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:17)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at d6.q0.handleMessage(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:408)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at android.os.Handler.dispatchMessage(Handler.java:102)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at android.os.Looper.loopOnce(Looper.java:201)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at android.os.Looper.loop(Looper.java:288)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at android.os.HandlerThread.run(HandlerThread.java:67)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):   Caused by: z5.x: Response code: 403
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at b6.a.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:310)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at z5.n.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:310)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at z5.e0.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:3)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at a6.f.n(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:266)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at a6.f.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:176)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at a6.f.n(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:266)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at a6.f.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:176)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at z5.c0.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:555)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at z5.d0.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:9)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at m6.o0.a(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:24)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at p6.i.run(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:35)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-31 17:24:48.559 E/ExoPlayerImplInternal(10145):       at java.lang.Thread.run(Thread.java:1012)
12-31 17:24:48.647 D/YTPlayerUtils(10145): Fetching player response for videoId: gGHU9TSUdVQ, playlistId: null
12-31 17:24:48.648 D/YTPlayerUtils(10145): Getting signature timestamp for videoId: gGHU9TSUdVQ
12-31 17:24:48.649 D/YTPlayerUtils(10145): Signature timestamp obtained: 20348
12-31 17:24:48.649 D/YTPlayerUtils(10145): Signature timestamp: 20348
12-31 17:24:48.649 D/YTPlayerUtils(10145): Session authentication status: Logged in
12-31 17:24:48.649 D/YTPlayerUtils(10145): Attempting to get player response using MAIN_CLIENT: ANDROID_VR
12-31 17:24:48.746 D/YTPlayerUtils(10145): Trying stream from MAIN_CLIENT: ANDROID_VR
12-31 17:24:48.746 D/YTPlayerUtils(10145): Player response status not OK: LOGIN_REQUIRED, reason: Sign in to confirm you’re not a bot
12-31 17:24:48.746 D/YTPlayerUtils(10145): Trying fallback client 1/11: ANDROID_VR
12-31 17:24:48.746 D/YTPlayerUtils(10145): Fetching player response for fallback client: ANDROID_VR
12-31 17:24:48.819 D/YTPlayerUtils(10145): Player response status not OK: LOGIN_REQUIRED, reason: Sign in to confirm you’re not a bot
12-31 17:24:48.819 D/YTPlayerUtils(10145): Trying fallback client 2/11: WEB_REMIX
12-31 17:24:48.819 D/YTPlayerUtils(10145): Fetching player response for fallback client: WEB_REMIX
12-31 17:24:49.090 E/Util    (10145): The service must be declared with a foregroundServiceType that includes mediaPlayback
12-31 17:24:49.100 E/MSessionService(10145): Failed to start foreground
12-31 17:24:49.100 E/MSessionService(10145):   android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.vivi.vivimusic/com.music.vivi.playback.MusicService
12-31 17:24:49.100 E/MSessionService(10145):       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
12-31 17:24:49.100 E/MSessionService(10145):       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Parcel.readParcelableInternal(Parcel.java:4816)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Parcel.readParcelable(Parcel.java:4778)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Parcel.createException(Parcel.java:2995)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Parcel.readException(Parcel.java:2978)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Parcel.readException(Parcel.java:2920)
12-31 17:24:49.100 E/MSessionService(10145):       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6114)
12-31 17:24:49.100 E/MSessionService(10145):       at android.app.Service.startForeground(Service.java:797)
12-31 17:24:49.100 E/MSessionService(10145):       at w5.z.a(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:1)
12-31 17:24:49.100 E/MSessionService(10145):       at d8.t1.d(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:50)
12-31 17:24:49.100 E/MSessionService(10145):       at d6.d0.run(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:272)
12-31 17:24:49.100 E/MSessionService(10145):       at w5.a0.L(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:22)
12-31 17:24:49.100 E/MSessionService(10145):       at d8.c0.execute(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:33)
12-31 17:24:49.100 E/MSessionService(10145):       at d8.p1.run(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:1340)
12-31 17:24:49.100 E/MSessionService(10145):       at w5.a0.L(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:22)
12-31 17:24:49.100 E/MSessionService(10145):       at wd.f.S(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:82)
12-31 17:24:49.100 E/MSessionService(10145):       at wd.f.T(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:10)
12-31 17:24:49.100 E/MSessionService(10145):       at d8.s1.C(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:22)
12-31 17:24:49.100 E/MSessionService(10145):       at d8.g0.i(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:12)
12-31 17:24:49.100 E/MSessionService(10145):       at d8.n0.handleMessage(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:57)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Handler.dispatchMessage(Handler.java:102)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Looper.loopOnce(Looper.java:201)
12-31 17:24:49.100 E/MSessionService(10145):       at android.os.Looper.loop(Looper.java:288)
12-31 17:24:49.100 E/MSessionService(10145):       at android.app.ActivityThread.main(ActivityThread.java:7966)
12-31 17:24:49.100 E/MSessionService(10145):       at java.lang.reflect.Method.invoke(Native Method)
12-31 17:24:49.100 E/MSessionService(10145):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-31 17:24:49.100 E/MSessionService(10145):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
12-31 17:24:49.181 D/YTPlayerUtils(10145): Player response status OK for client: WEB_REMIX
12-31 17:24:49.189 D/YTPlayerUtils(10145): Finding format with audioQuality: HIGH, network metered: false
12-31 17:24:49.189 D/YTPlayerUtils(10145): Selected format: audio/webm; codecs="opus", bitrate: 145448
12-31 17:24:49.189 D/YTPlayerUtils(10145): Format found: audio/webm; codecs="opus", bitrate: 145448
12-31 17:24:49.189 D/YTPlayerUtils(10145): Finding stream URL for format: audio/webm; codecs="opus", videoId: gGHU9TSUdVQ
12-31 17:24:49.252 D/AndroidRuntime(10145): Shutting down VM
--------- beginning of crash
12-31 17:24:49.254 E/AndroidRuntime(10145): FATAL EXCEPTION: main
12-31 17:24:49.254 E/AndroidRuntime(10145): Process: com.vivi.vivimusic, PID: 10145
12-31 17:24:49.254 E/AndroidRuntime(10145): android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.vivi.vivimusic/com.music.vivi.playback.MusicService
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4816)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Parcel.readParcelable(Parcel.java:4778)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Parcel.createException(Parcel.java:2995)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Parcel.readException(Parcel.java:2978)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Parcel.readException(Parcel.java:2920)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5337)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1901)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1877)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at d8.t1.d(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:39)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at d8.q1.run(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:80)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at w5.a0.L(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:22)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at d8.c0.execute(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:33)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at d8.n.e(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:49)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at pc.u.run(r8-map-id-410f72caeade909566cfc51a26a6fe4f9c8173e69e5b93dc8a4daae7099b949c:615)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Handler.handleCallback(Handler.java:942)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Looper.loopOnce(Looper.java:201)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.os.Looper.loop(Looper.java:288)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at android.app.ActivityThread.main(ActivityThread.java:7966)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at java.lang.reflect.Method.invoke(Native Method)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-31 17:24:49.254 E/AndroidRuntime(10145): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
12-31 17:24:49.309 D/YTPlayerUtils(10145): Stream URL obtained successfully
12-31 17:24:49.309 D/YTPlayerUtils(10145): Stream expires in: 21540 seconds
12-31 17:24:49.309 D/YTPlayerUtils(10145): Validating stream URL status
12-31 17:24:49.452 I/CrashLogHandler(10145): Crash log saved to: /storage/emulated/0/Android/data/com.vivi.vivimusic/files/crash_logs/crash_2025-12-31_17-24-49.txt
12-31 17:24:49.459 D/YTPlayerUtils(10145): Stream URL validation result: Failed (403)
12-31 17:24:49.459 D/YTPlayerUtils(10145): Stream validation failed for client: WEB_REMIX
12-31 17:24:49.459 D/YTPlayerUtils(10145): Trying fallback client 3/11: ANDROID_CREATOR
12-31 17:24:49.459 D/YTPlayerUtils(10145): Fetching player response for fallback client: ANDROID_CREATOR
12-31 17:24:49.514 D/YTPlayerUtils(10145): Player response status not OK: null, reason: null
12-31 17:24:49.514 D/YTPlayerUtils(10145): Trying fallback client 4/11: IOS
12-31 17:24:49.514 D/YTPlayerUtils(10145): Fetching player response for fallback client: IOS
12-31 17:24:49.607 D/YTPlayerUtils(10145): Player response status not OK: LOGIN_REQUIRED, reason: Sign in to confirm you’re not a bot
12-31 17:24:49.607 D/YTPlayerUtils(10145): Trying fallback client 5/11: ANDROID_VR
12-31 17:24:49.607 D/YTPlayerUtils(10145): Fetching player response for fallback client: ANDROID_VR
12-31 17:24:49.681 D/YTPlayerUtils(10145): Player response status not OK: LOGIN_REQUIRED, reason: Sign in to confirm you’re not a bot
12-31 17:24:49.681 D/YTPlayerUtils(10145): Trying fallback client 6/11: ANDROID
12-31 17:24:49.681 D/YTPlayerUtils(10145): Fetching player response for fallback client: ANDROID

**Comment by vivizzz007** [comment]
can you send the link that failed to play the song for testing purpose

**Comment by Trisn0802** [comment]
> can you send the link that failed to play the song for testing purpose

https://music.youtube.com/watch?v=gGHU9TSUdVQ

**Comment by vivizzz007** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/86a4dee0-91b5-46b9-bbb4-1fe14868c01a" />
fixed the error response 403

**Comment by Trisn0802** [comment]
<!-- Uploading "screen-20260104-003302.mp4"... ->

I checked the song but the result is still the same

**Comment by renzzr** [comment]
why is it down rn

**Comment by vivizzz007** [comment]
@renzzr???

**Comment by renzzr** [comment]
It's down right now. I can't even do anything because it just keeps loading and frequently crashes. I have good internet; other music apps work just fine.

**Comment by vivizzz007** [comment]
using the latest beta?
just clear the app data and cache it would work fine

**Comment by renzzr** [comment]
i tried everything i cleared cache data and also re install i restarted my phone it just doesn't work

**Comment by vivizzz007** [comment]
do your country support ytmusic if yes then it would work perfectly. becoz currently i have tested and the testers also said working fine

**Comment by renzzr** [comment]
> do your country support ytmusic if yes then it would work perfectly. becoz currently i have tested and the testers also said working fine

yeah im from Philippines

**Comment by vivizzz007** [comment]
grab log or login to app and check

**Comment by renzzr** [comment]
YouTube Music works just fine.

**Comment by vivizzz007** [comment]
@renzzr send me an video to my gmail

**Comment by renzzr** [comment]
hey do u have discord or something can we talk there? its hard ih here and
i cant send videos

**Comment by vivizzz007** [comment]
gmail me bro place the video in your drive and send me

**Comment by renzzr** [comment]
Screen_Recording_20260105_175626_VIVI.mp4
<https://drive.google.com/file/d/1-Z3rpixniKF9STiy7wbd_7vOYsdSY9hH/view?usp=drivesdk>

**Comment by vivizzz007** [comment]
make the video public

**Comment by renzzr** [comment]
there thanks

**Comment by vivizzz007** [comment]
do one thing grab log using 
https://play.google.com/store/apps/details?id=com.technoify.logviewer&hl=en_IN
or any other and send me mail i would look into it

**Comment by renzzr** [comment]
the app keeps crashing i cant

**Comment by vivizzz007** [comment]
in the video i didin't see any crash 👀

**Comment by vivizzz007** [comment]
@renzzr by the by clear app data also then try again wait for 1 or 2 second

**Comment by renzzr** [comment]
no i meant the log viewer app i download it can't grab log

**Comment by vivizzz007** [comment]
use some other app

**Comment by renzzr** [comment]
> use some other app

=== CRASH REPORT ===
Timestamp: 2026-01-05 22:33:13

=== DEVICE INFO ===
Device: samsung SM-S721B
Android Version: 16 (API 36)
Brand: samsung
Product: r12sxxx
CPU ABI: arm64-v8a

=== APP INFO ===
Package: com.vivi.vivimusic
Version: 5.0.0 (59)

=== THREAD INFO ===
Thread Name: main
Thread ID: 2

=== EXCEPTION ===
Exception Type: java.lang.IllegalStateException
Message: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: 3f26cfef100f457bc0d0770cd5406cf2, found: 77118ea292614a4db192780d42629896

=== STACK TRACE ===
java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: 3f26cfef100f457bc0d0770cd5406cf2, found: 77118ea292614a4db192780d42629896
	at n8.u.f(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:122)
	at z8.f.onOpen(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:27)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:554)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:439)
	at z8.f.c(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:76)
	at z8.f.b(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:24)
	at z8.g.getWritableDatabase(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:10)
	at q8.b.I0(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:14)
	at n8.x.r(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:7)
	at n8.q0.f(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:75)
	at n8.i0.invokeSuspend(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:751)
	at th.a.resumeWith(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:9)
	at pi.o0.run(r8-map-id-7fd005b56a300774af6cfc5bc8f8f337e4e76aebc6bf22f6a9f562a17549c7d0:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
	at java.lang.Thread.run(Thread.java:1119)
	Suppressed: vi.e: [t2.a2@d589fc0, h1.e@de8b4f9, w1{Cancelling}@4cf1c3e, r0@cbe1a9f]

**Comment by vivizzz007** [comment]
by the by are using beta version or stable version 
did you updated beta and then gone to stable?

**Comment by vivizzz007** [comment]
@renzzr did you clear data?

**Comment by vivizzz007** [comment]
@renzzr https://github.com/vivizzz007/vivi-music/releases/download/b5.0.0/vivibeta1.apk use this version this would fix all the issue
